name: 📚 Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Pentora's documentation!

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Unclear or confusing
        - Incorrect or outdated
        - Broken links
        - Typo or grammar
        - Code example doesn't work
        - Need more examples
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the issue?
      options:
        - README.md
        - CLAUDE.md (development guide)
        - CLI help text
        - Code comments
        - KNOWN-ISSUES.md
        - PLAN.md
        - Plugin documentation
        - API documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: What's wrong or missing?
      placeholder: |
        The README doesn't explain how to use the --vuln flag. Users don't know they need to run `pentora plugin update` first.
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (if applicable)
      description: Quote the current documentation
      placeholder: |
        ```markdown
        ## Usage

        pentora scan --targets 192.168.1.0/24
        ```

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Improvement
      description: How should it be changed?
      placeholder: |
        ```markdown
        ## Usage

        ### Basic Scan
        pentora scan --targets 192.168.1.0/24

        ### Vulnerability Scan
        First, download vulnerability plugins:
        ```bash
        pentora plugin update
        ```

        Then run scan with vulnerability detection:
        ```bash
        pentora scan --targets 192.168.1.0/24 --vuln
        ```
        ```

  - type: input
    id: file-path
    attributes:
      label: File Path
      description: Exact location of the issue
      placeholder: "README.md:45-50 or pkg/scanner/scanner.go:123"

  - type: textarea
    id: related-docs
    attributes:
      label: Related Documentation
      description: Links to related docs that might need updating
      placeholder: |
        - CLI help text for `pentora scan`
        - Plugin documentation in pentora-plugins repo
        - CLAUDE.md section on plugins

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help fix this?
      options:
        - label: I can submit a PR to fix this
        - label: I need help understanding the technical details
        - label: I can review the changes

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: This confused me as a new user trying to get started
